replicaCount: 1

image:
  repository: goshaker/wordpress
  tag: v0.0.7
  #registry: docker.io
  #repository: bitnami/wordpress
  #tag: 6.5.0-debian-12-r2
  #pullPolicy: IfNotPresent
  #debug: false
  
service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wordpress.k8s-7.sa

persistentVolumeClaim:
  storageSize: 8Gi

env:
  - name: WORDPRESS_DATABASE_HOST
    value: 192.168.203.4
  - name: WORDPRESS_DATABASE_NAME
    value: wordpress
  - name: WORDPRESS_DATABASE_USER
    value: wordpress
  - name: WORDPRESS_DATABASE_PASSWORD
    value: wordpress

      #nfs:
      #server: 192.168.37.105
      #path: "/mnt/IT-Academy/nfs-data/sa2-27-24/gakobiakov/wordpress"
      #readOnly: false
      #vers: 3
