name: project-pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: ci-cd project
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          
      - name: "Hadolint"
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "./docker/Dockerfile"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Log in to the Docker hub
        uses: docker/login-action@v3
        with:
          username: goshaker
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: |
            goshaker/wordpress:${{steps.tag_version.outputs.new_tag}}
          
      - name: set up Helm
        uses: azure/setup-helm@v4.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          
      - name: helm-check
        uses: igabaydulin/helm-check-action@0.2.0
        env:
          CHART_LOCATION: ./helm-sources/wordpress
          CHART_VALUES: ./helm-sources/wordpress/values.yaml   
      
      - name: Publish Helm charts
        run: |
          cd helm-source/
          helm package wordpress --version=${{ steps.tag_version.outputs.new_tag }} --app-version=${{ steps.tag_version.outputs.new_tag }}
          mv wordpress-* ../helm-release
          cd ..
          helm repo index --url https://github.com/Goshaker/project --merge index.yaml .
     
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "Publish wordpress:${{ steps.tag_version.outputs.new_tag }}"
          git push origin master
